"use client";

import { useState } from "react";
import { FiAlertTriangle, FiCheckCircle, FiInfo, FiEdit3, FiCheck, FiX } from "react-icons/fi";
import React from "react"; // Added missing import

interface ResumeAnalysisProps {
  analysisResults: {
    overallScore: number;
    sectionScores: {
      summary: number;
      workExperience: number;
      skills: number;
      education: number;
      achievements: number;
      contactInfo: number;
      certifications: number;
      languages: number;
      projects: number;
      volunteerWork: number;
    };
    suggestions: {
      summary: string;
      workExperience: string;
      skills: string;
      education: string;
      achievements: string;
      contactInfo: string;
      certifications: string;
      languages: string;
      projects: string;
      volunteerWork: string;
    };
    improvedContent?: {
      [key: string]: string;
    };
  };
  resumeText: string;
  onContentUpdate?: (updatedText: string) => void;
}

export function ResumeAnalysis({ analysisResults, resumeText, onContentUpdate }: ResumeAnalysisProps) {
  const [activeTab, setActiveTab] = useState<"score" | "content">("score");
  const [hoveredLine, setHoveredLine] = useState<number | null>(null);
  const [editingLine, setEditingLine] = useState<number | null>(null);
  const [editContent, setEditContent] = useState("");
  const [resumeLines, setResumeLines] = useState<string[]>(resumeText.split("\n"));
  
  // Update resume lines when text changes
  React.useEffect(() => {
    setResumeLines(resumeText.split("\n"));
  }, [resumeText]);
  
  // Get suggestions for each line from the AI response
  const getSuggestionForLine = (lineIndex: number, lineContent: string): string[] | null => {
    // Check if we have an AI-generated suggestion for this line
    if (analysisResults.improvedContent && analysisResults.improvedContent[lineIndex]) {
      const suggestion = analysisResults.improvedContent[lineIndex];
      // If it's a string, convert to array; if it's already an array, use as is
      return Array.isArray(suggestion) ? suggestion : [suggestion];
    }
    
    // Grammar and content improvement suggestions
    const suggestions: string[] = [];
    
    // Grammar checks
    if (lineContent.includes("i ") && !lineContent.includes("I ")) {
      suggestions.push("Capitalize 'I' when referring to yourself");
    }
    if (lineContent.includes("  ")) {
      suggestions.push("Remove extra spaces");
    }
    if (lineContent.endsWith(".") && !lineContent.match(/[.!?]$/)) {
      suggestions.push("Add proper punctuation");
    }
    
    // Content improvement suggestions
    if (lineContent.includes("Manager") || lineContent.includes("manager")) {
      suggestions.push("Led cross-functional team of 5 engineers, resulting in 30% increase in product delivery speed.");
    }
    if (lineContent.includes("Developed") || lineContent.includes("developed")) {
      suggestions.push("Engineered scalable solutions that reduced system latency by 45% and increased user retention by 22%.");
    }
    if (lineContent.includes("Skills") || lineContent.includes("skills")) {
      suggestions.push("Expert in React, TypeScript, Node.js, AWS, CI/CD, and performance optimization.");
    }
    
    // Quantification suggestions
    if (lineContent.includes("improved") || lineContent.includes("increased") || lineContent.includes("reduced")) {
      if (!lineContent.match(/\d+%|\d+ percent/)) {
        suggestions.push("Add specific metrics and percentages to quantify your impact");
      }
    }
    
    return suggestions.length > 0 ? suggestions : null;
  };

  // Check if a line has improvements
  const hasImprovement = (lineIndex: number) => {
    return analysisResults.improvedContent && analysisResults.improvedContent[lineIndex];
  };

  // Download report function
  const downloadReport = () => {
    // Create a comprehensive report with overall score and section-wise scores
    const reportContent = `
Resume Analysis Report
Generated by ResumeCheck
${new Date().toLocaleDateString()}

OVERALL RESUME SCORE: ${analysisResults.overallScore}/100

SECTION-WISE SCORES:
${Object.entries(analysisResults.sectionScores)
  .map(([section, score]) => `${section.replace(/([A-Z])/g, ' $1').trim()}: ${score}/100`)
  .join('\n')}

DETAILED ANALYSIS:
${Object.entries(analysisResults.sectionScores)
  .map(([section, score]) => `
${section.replace(/([A-Z])/g, ' $1').trim()} (${score}/100):
${analysisResults.suggestions[section as keyof typeof analysisResults.suggestions]}
`)
  .join('\n')}

MISSING SECTIONS:
${missingSections.length > 0 ? missingSections.join(', ') : 'None detected'}

IMPROVEMENT OPPORTUNITIES:
${Object.entries(analysisResults.sectionScores)
  .filter(([_, score]) => score < 80)
  .map(([section, score]) => `${section.replace(/([A-Z])/g, ' $1').trim()}: ${score}/100 - ${analysisResults.suggestions[section as keyof typeof analysisResults.suggestions]}`)
  .join('\n')}

---
Watermark: ResumeCheck - Professional Resume Analysis Tool
Generated on: ${new Date().toLocaleString()}
    `.trim();

    // Create blob and download
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `resume-analysis-report-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };
  
  const handleLineClick = (lineIndex: number, suggestions: string[] | null) => {
    if (suggestions && suggestions.length > 0) {
      // If there are multiple suggestions, use the first one as default
      setEditingLine(lineIndex);
      setEditContent(suggestions[0]);
    }
  };
  
  const handleSaveEdit = (lineIndex: number) => {
    if (onContentUpdate) {
      const updatedLines = [...resumeLines];
      updatedLines[lineIndex] = editContent;
      const updatedText = updatedLines.join('\n');
      onContentUpdate(updatedText);
    }
    
    setEditingLine(null);
    setEditContent("");
  };
  
  const handleCancelEdit = () => {
    setEditingLine(null);
    setEditContent("");
  };

  const getSectionScoreColor = (score: number) => {
    if (score >= 80) return "text-green-500 dark:text-green-400";
    if (score >= 60) return "text-yellow-500 dark:text-yellow-400";
    return "text-red-500 dark:text-red-400";
  };

  const getScoreIcon = (score: number) => {
    if (score >= 80) return <FiCheckCircle className="h-5 w-5 text-green-500 dark:text-green-400" />;
    if (score >= 60) return <FiInfo className="h-5 w-5 text-yellow-500 dark:text-yellow-400" />;
    return <FiAlertTriangle className="h-5 w-5 text-red-500 dark:text-red-400" />;
  };

  // Function to detect missing resume sections
  const getMissingSections = () => {
    const missingSections: string[] = [];
    const resumeTextLower = resumeText.toLowerCase();
    
    // Check for common resume sections
    const sectionChecks = [
      { name: 'Professional Summary', keywords: ['summary', 'objective', 'profile', 'overview'] },
      { name: 'Work Experience', keywords: ['experience', 'employment', 'work history', 'career'] },
      { name: 'Education', keywords: ['education', 'degree', 'university', 'college', 'school'] },
      { name: 'Skills', keywords: ['skills', 'technical skills', 'competencies', 'expertise'] },
      { name: 'Achievements', keywords: ['achievements', 'accomplishments', 'awards', 'recognition'] },
      { name: 'Contact Information', keywords: ['email', 'phone', 'address', 'linkedin', 'github'] },
      { name: 'Certifications', keywords: ['certification', 'certified', 'license', 'accreditation'] },
      { name: 'Languages', keywords: ['languages', 'fluent', 'proficient', 'bilingual'] },
      { name: 'Projects', keywords: ['projects', 'portfolio', 'case studies', 'work samples'] },
      { name: 'Volunteer Work', keywords: ['volunteer', 'community service', 'charity', 'non-profit'] }
    ];
    
    sectionChecks.forEach(section => {
      const hasSection = section.keywords.some(keyword => resumeTextLower.includes(keyword));
      if (!hasSection) {
        missingSections.push(section.name);
      }
    });
    
    return missingSections;
  };

  const missingSections = getMissingSections();

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="col-span-2 rounded-lg border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-800 dark:bg-gray-900">
          <div className="flex flex-col md:flex-row md:items-center md:justify-between">
            <div className="mb-4 md:mb-0">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white">Overall Resume Score</h2>
              <p className="text-gray-600 dark:text-gray-400 mt-1">
                Based on industry standards and best practices
              </p>
            </div>
            <div className="relative flex justify-center">
              <svg viewBox="0 0 36 36" className="h-28 w-28">
                <path
                  className="stroke-current text-gray-200 dark:text-gray-700"
                  fill="none"
                  strokeWidth="3"
                  d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                />
                <path
                  className={`stroke-current ${
                    analysisResults.overallScore >= 80
                      ? "text-green-500"
                      : analysisResults.overallScore >= 60
                      ? "text-yellow-500"
                      : "text-red-500"
                  }`}
                  fill="none"
                  strokeWidth="3"
                  strokeDasharray={`${analysisResults.overallScore}, 100`}
                  d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                />
                <text
                  x="18"
                  y="19"
                  className="fill-current text-xs font-bold text-gray-800 dark:text-white"
                  textAnchor="middle"
                >
                  {analysisResults.overallScore}
                </text>
                <text
                  x="18"
                  y="26"
                  className="fill-current text-[0.45rem] font-medium text-gray-400 dark:text-gray-500"
                  textAnchor="middle"
                >
                  SCORE
                </text>
              </svg>
              <div className="absolute bottom-1 right-1 rounded-full bg-blue-100 p-1.5 dark:bg-blue-900">
                {getScoreIcon(analysisResults.overallScore)}
              </div>
            </div>
          </div>
          
          <div className="mt-6 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {Object.entries(analysisResults.sectionScores).map(([section, score]) => (
              <div 
                key={section} 
                className="flex items-center p-3 rounded-lg border border-gray-100 dark:border-gray-800 bg-gray-50 dark:bg-gray-900"
              >
                <div className={`h-8 w-8 rounded-full flex items-center justify-center mr-3 ${ 
                  score >= 80
                    ? "bg-green-100 text-green-600 dark:bg-green-900/30 dark:text-green-400"
                    : score >= 60
                    ? "bg-yellow-100 text-yellow-600 dark:bg-yellow-900/30 dark:text-yellow-400"
                    : "bg-red-100 text-red-600 dark:bg-red-900/30 dark:text-red-400"
                }`}>
                  {getScoreIcon(score)}
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium text-gray-900 dark:text-white capitalize">
                    {section.replace(/([A-Z])/g, ' $1').trim()}
                  </p>
                  <p className="text-xs text-gray-500 dark:text-gray-400">
                    Score: {score}/100
                  </p>
                </div>
              </div>
            ))}
          </div>
          
          {/* Missing Sections Alert */}
          {missingSections.length > 0 && (
            <div className="mt-6 p-4 rounded-lg border border-amber-200 bg-amber-50 dark:border-amber-800 dark:bg-amber-900/20">
              <div className="flex items-start">
                <FiAlertTriangle className="h-5 w-5 text-amber-600 dark:text-amber-400 mt-0.5 mr-3 flex-shrink-0" />
                <div className="flex-1">
                  <h3 className="text-sm font-medium text-amber-800 dark:text-amber-200">
                    Missing Resume Sections
                  </h3>
                  <p className="text-sm text-amber-700 dark:text-amber-300 mt-1">
                    Consider adding these sections to improve your resume completeness:
                  </p>
                  <div className="mt-2 flex flex-wrap gap-2">
                    {missingSections.map((section, index) => (
                      <span
                        key={index}
                        className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-200"
                      >
                        {section}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
        
        <div className="rounded-lg border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-800 dark:bg-gray-900">
          <h3 className="text-xl font-bold mb-4 text-gray-900 dark:text-white">Quick Actions</h3>
          <div className="space-y-3">
            <button
              className="inline-flex w-full items-center justify-center rounded-md bg-blue-600 px-4 py-3 text-sm font-medium text-white shadow-sm transition-colors hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 dark:focus:ring-offset-gray-900"
              onClick={() => {
                setActiveTab("score");
                setTimeout(() => {
                  // Find the tab navigation area (Section Scores | Resume Content & Editing)
                  const tabNavigation = document.querySelector('[data-tab-navigation]');
                  if (tabNavigation) {
                    const rect = tabNavigation.getBoundingClientRect();
                    const scrollTop = window.pageYOffset || document.documentElement.scrollTop;
                    const viewportHeight = window.innerHeight || document.documentElement.clientHeight;
                    // Scroll so that the tab navigation is centered in the viewport
                    window.scrollTo({
                      top: rect.top + scrollTop - (viewportHeight / 2) + (rect.height / 2),
                      behavior: "smooth"
                    });
                  }
                }, 100); // Wait for tab to render
              }}
            >
              View Section Scores
            </button>
            <button
              className="inline-flex w-full items-center justify-center rounded-md bg-green-600 px-4 py-3 text-sm font-medium text-white shadow-sm transition-colors hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2 dark:focus:ring-offset-gray-900"
              onClick={() => {
                setActiveTab("content");
                setTimeout(() => {
                  // Find the tab navigation area (Section Scores | Resume Content & Editing)
                  const tabNavigation = document.querySelector('[data-tab-navigation]');
                  if (tabNavigation) {
                    const rect = tabNavigation.getBoundingClientRect();
                    const scrollTop = window.pageYOffset || document.documentElement.scrollTop;
                    const viewportHeight = window.innerHeight || document.documentElement.clientHeight;
                    // Scroll so that the tab navigation is centered in the viewport
                    window.scrollTo({
                      top: rect.top + scrollTop - (viewportHeight / 2) + (rect.height / 2),
                      behavior: "smooth"
                    });
                  }
                }, 100); // Wait for tab to render
              }}
            >
              Edit Resume Content
            </button>
            <button
              className="inline-flex w-full items-center justify-center rounded-md border border-gray-300 bg-white px-4 py-3 text-sm font-medium text-gray-700 shadow-sm transition-colors hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-200 dark:hover:bg-gray-700 dark:focus:ring-offset-gray-900"
              onClick={downloadReport}
            >
              Download Report
            </button>
          </div>
        </div>
      </div>

      <div className="overflow-hidden rounded-lg border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-gray-900">
        <div className="border-b border-gray-200 dark:border-gray-800">
          <div data-tab-navigation className="flex">
            <button
              className={`px-8 py-4 text-sm font-medium focus:outline-none transition-colors ${
                activeTab === "score"
                  ? "border-b-2 border-blue-500 text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/20"
                  : "text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-100 hover:bg-gray-50 dark:hover:bg-gray-800"
              }`}
              onClick={() => setActiveTab("score")}
            >
              Section Scores
            </button>
            <button
              className={`px-8 py-4 text-sm font-medium focus:outline-none transition-colors ${
                activeTab === "content"
                  ? "border-b-2 border-blue-500 text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/20"
                  : "text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-100 hover:bg-gray-50 dark:hover:bg-gray-800"
              }`}
              onClick={() => setActiveTab("content")}
            >
              Resume Content & Editing
            </button>
          </div>
        </div>

        <div className="p-6 bg-white dark:bg-gray-900">
          {activeTab === "score" ? (
            <div id="section-scores" className="space-y-8">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {Object.entries(analysisResults.sectionScores).map(([section, score]) => (
                  <div 
                    key={section} 
                    className="rounded-lg border border-gray-100 dark:border-gray-800 bg-white dark:bg-gray-900 p-5 shadow-sm"
                  >
                    <div className="flex items-center justify-between mb-3">
                      <div className="flex items-center space-x-3">
                        <div className={`h-8 w-8 rounded-full flex items-center justify-center ${
                          score >= 80
                            ? "bg-green-100 text-green-600 dark:bg-green-900/30 dark:text-green-400"
                            : score >= 60
                            ? "bg-yellow-100 text-yellow-600 dark:bg-yellow-900/30 dark:text-yellow-400"
                            : "bg-red-100 text-red-600 dark:bg-red-900/30 dark:text-red-400"
                        }`}>
                          {getScoreIcon(score)}
                        </div>
                        <h3 className="text-lg font-bold capitalize text-gray-900 dark:text-white">
                          {section.replace(/([A-Z])/g, " $1").trim()}
                        </h3>
                      </div>
                      <span className={`text-xl font-bold ${getSectionScoreColor(score)}`}>
                        {score}
                      </span>
                    </div>
                    
                    <div className="mb-4">
                      <div className="flex justify-between text-xs mb-1">
                        <span className="text-gray-500 dark:text-gray-400">Poor</span>
                        <span className="text-gray-500 dark:text-gray-400">Excellent</span>
                      </div>
                      <div className="h-2.5 w-full rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden">
                        <div
                          className={`h-2.5 rounded-full ${
                            score >= 80
                              ? "bg-green-500"
                              : score >= 60
                              ? "bg-yellow-500"
                              : "bg-red-500"
                          }`}
                          style={{ width: `${score}%` }}
                        ></div>
                      </div>
                    </div>
                    
                    <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-4 border border-gray-100 dark:border-gray-700">
                      <h4 className="text-sm font-medium mb-2 text-gray-700 dark:text-gray-300">Suggestions:</h4>
                      <p className="text-sm text-gray-600 dark:text-gray-400">
                        {analysisResults.suggestions[section as keyof typeof analysisResults.suggestions]}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Improvement Opportunities */}
                <div className="rounded-lg border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-800 dark:bg-gray-900">
                  <h3 className="text-lg font-bold mb-4 text-gray-900 dark:text-white">Improvement Opportunities</h3>
                  <ul className="space-y-4">
                    {Object.entries(analysisResults.sectionScores)
                      .filter(([_, score]) => score < 80)
                      .map(([section, score]) => (
                        <li key={section} className="flex items-start space-x-3 p-3 rounded-lg bg-gray-50 dark:bg-gray-800">
                          <div className={`mt-0.5 h-6 w-6 rounded-full flex items-center justify-center flex-shrink-0 ${
                            score >= 60
                              ? "bg-yellow-100 text-yellow-600 dark:bg-yellow-900/30 dark:text-yellow-400"
                              : "bg-red-100 text-red-600 dark:bg-red-900/30 dark:text-red-400"
                          }`}>
                            {getScoreIcon(score)}
                          </div>
                          <div>
                            <p className="text-sm font-medium capitalize text-gray-900 dark:text-white">
                              {section.replace(/([A-Z])/g, " $1").trim()}
                            </p>
                            <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">
                              {analysisResults.suggestions[section as keyof typeof analysisResults.suggestions]}
                            </p>
                            <button 
                              className="mt-2 text-sm text-blue-600 hover:text-blue-500 dark:text-blue-400 font-medium flex items-center"
                              onClick={() => setActiveTab("content")}
                            >
                              Improve Now <span className="ml-1">→</span>
                            </button>
                          </div>
                        </li>
                      ))}
                  </ul>
                </div>
                
                {/* Actions */}
                <div className="rounded-lg border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-800 dark:bg-gray-900">
                  <h3 className="text-lg font-bold mb-4 text-gray-900 dark:text-white">AI-Powered Actions</h3>
                  <div className="space-y-4">
                    <button
                      className="inline-flex w-full items-center justify-center rounded-md bg-blue-600 px-4 py-3 text-sm font-medium text-white shadow-sm transition-colors hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 dark:focus:ring-offset-gray-900"
                      onClick={() => setActiveTab("content")}
                    >
                      Apply All Improvements
                    </button>
                    <button
                      className="inline-flex w-full items-center justify-center rounded-md bg-green-600 px-4 py-3 text-sm font-medium text-white shadow-sm transition-colors hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2 dark:focus:ring-offset-gray-900"
                    >
                      Generate Optimized CV
                    </button>
                    <div className="mt-3 p-3 bg-gray-50 dark:bg-gray-800 rounded-lg border border-gray-100 dark:border-gray-700">
                      <p className="text-sm text-gray-600 dark:text-gray-400">
                        Generate an optimized version of your resume with AI improvements tailored to your industry and target role.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ) : (
            <div className="space-y-6">
              <div className="bg-blue-50 dark:bg-blue-900/20 rounded-lg p-4 border border-blue-100 dark:border-blue-800">
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-3">
                    <div className="bg-blue-100 dark:bg-blue-800 p-2 rounded-full">
                      <FiInfo className="h-5 w-5 text-blue-600 dark:text-blue-400" />
                    </div>
                    <p className="text-sm font-medium text-blue-800 dark:text-blue-300">
                      Hover over each line to see AI-powered suggestions. Click on a suggestion to apply it instantly.
                    </p>
                  </div>
                  <div className="flex items-center space-x-3 text-xs text-gray-500">
                    <div className="flex items-center space-x-1.5">
                      <div className="h-3 w-3 rounded-full bg-yellow-400"></div>
                      <span className="font-medium">Grammar</span>
                    </div>
                    <div className="flex items-center space-x-1.5">
                      <div className="h-3 w-3 rounded-full bg-blue-400"></div>
                      <span className="font-medium">Content</span>
                    </div>
                  </div>
                </div>
              </div>
              
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                <div className="rounded-lg border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-gray-900 overflow-hidden">
                  <div className="bg-gray-100 dark:bg-gray-800 px-5 py-3 border-b border-gray-200 dark:border-gray-700 flex justify-between items-center">
                    <h3 className="font-medium text-gray-900 dark:text-white">Resume Content</h3>
                    <div className="flex space-x-2">
                      <button className="text-xs bg-blue-600 text-white px-3 py-1.5 rounded-md hover:bg-blue-700 transition-colors font-medium">
                        Apply All Suggestions
                      </button>
                    </div>
                  </div>
                  <div className="max-h-[500px] overflow-y-auto p-5 font-mono text-sm bg-gray-50 dark:bg-gray-900">
                    {/* Display original formatted content with AI suggestions highlighted */}
                    <div className="space-y-4">
                      {resumeLines.map((line, index) => {
                        const suggestions = getSuggestionForLine(index, line);
                        const hasImprovements = hasImprovement(index);
                        
                        return (
                          <div key={index} className="group relative">
                            {/* Original text with highlighting */}
                            <div
                              className={`whitespace-pre-wrap py-3 px-4 rounded-lg border transition-all ${
                                hasImprovements
                                  ? 'bg-yellow-50 dark:bg-yellow-900/20 border-yellow-200 dark:border-yellow-700'
                                  : suggestions
                                  ? 'bg-blue-50 dark:bg-blue-900/20 border-blue-200 dark:border-blue-700'
                                  : 'bg-white dark:bg-gray-800 border-gray-200 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-700'
                              }`}
                              onMouseEnter={() => setHoveredLine(index)}
                              onMouseLeave={() => setHoveredLine(null)}
                            >
                              {/* Line number and content */}
                              <div className="flex items-start justify-between mb-2">
                                <span className="text-xs font-medium text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-gray-700 px-2 py-1 rounded">
                                  Line {index + 1}
                                </span>
                                {hasImprovements && (
                                  <span className="inline-flex items-center rounded-full bg-yellow-100 px-2 py-1 text-xs font-medium text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200">
                                    ✨ AI Improved
                                  </span>
                                )}
                                {suggestions && !hasImprovements && (
                                  <span className="inline-flex items-center rounded-full bg-blue-100 px-2 py-1 text-xs font-medium text-blue-800 dark:bg-blue-900 dark:text-blue-200">
                                    💡 Suggestions Available
                                  </span>
                                )}
                              </div>
                              
                              {/* Original text */}
                              <div className="text-gray-900 dark:text-gray-200 font-mono leading-relaxed">
                                {line || "\u00A0"}
                              </div>
                              
                              {/* AI Suggestions display */}
                              {suggestions && (
                                <div className="mt-3 pt-3 border-t border-gray-200 dark:border-gray-600">
                                  <div className="flex items-center justify-between mb-2">
                                    <h5 className="text-sm font-medium text-gray-700 dark:text-gray-300">
                                      AI Suggestions:
                                    </h5>
                                    <button
                                      onClick={() => handleLineClick(index, suggestions)}
                                      className="text-xs bg-blue-600 text-white px-3 py-1.5 rounded-md hover:bg-blue-700 transition-colors font-medium opacity-0 group-hover:opacity-100"
                                    >
                                      Apply Best
                                    </button>
                                  </div>
                                  <ul className="space-y-2">
                                    {suggestions.map((suggestion, idx) => (
                                      <li key={idx} className="flex items-start space-x-2 bg-white dark:bg-gray-700 p-2 rounded border border-gray-100 dark:border-gray-600">
                                        <div className="mt-1.5 h-2 w-2 rounded-full bg-blue-400 flex-shrink-0"></div>
                                        <p className="text-sm text-gray-600 dark:text-gray-400">{suggestion}</p>
                                      </li>
                                    ))}
                                  </ul>
                                </div>
                              )}
                              
                              {/* Edit button */}
                              <div className="mt-3 flex justify-end">
                                <button
                                  onClick={() => {
                                    setEditingLine(index);
                                    setEditContent(line);
                                  }}
                                  className="text-xs bg-gray-600 text-white px-3 py-1.5 rounded-md hover:bg-gray-700 transition-colors font-medium opacity-0 group-hover:opacity-100"
                                >
                                  Edit Line
                                </button>
                              </div>
                            </div>
                            
                            {/* Editing interface */}
                            {editingLine === index && (
                              <div className="mt-3 p-4 bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700">
                                <textarea
                                  value={editContent}
                                  onChange={(e) => setEditContent(e.target.value)}
                                  className="w-full rounded-md border border-gray-300 bg-white p-3 text-sm font-mono dark:border-gray-600 dark:bg-gray-700 dark:text-white"
                                  rows={3}
                                />
                                <div className="flex justify-end space-x-3 mt-3">
                                  <button
                                    onClick={handleCancelEdit}
                                    className="flex items-center space-x-1.5 rounded-md bg-gray-200 px-4 py-1.5 text-xs font-medium hover:bg-gray-300 dark:bg-gray-700 dark:hover:bg-gray-600 transition-colors"
                                  >
                                    <FiX className="h-3.5 w-3.5" />
                                    <span>Cancel</span>
                                  </button>
                                  <button
                                    onClick={() => handleSaveEdit(index)}
                                    className="flex items-center space-x-1.5 rounded-md bg-blue-600 px-4 py-1.5 text-xs font-medium text-white hover:bg-blue-700 transition-colors"
                                  >
                                    <FiCheck className="h-3.5 w-3.5" />
                                    <span>Apply Changes</span>
                                  </button>
                                </div>
                              </div>
                            )}
                          </div>
                        );
                      })}
                    </div>
                  </div>
                </div>
                
                <div className="rounded-lg border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-gray-900 overflow-hidden">
                  <div className="bg-gray-100 dark:bg-gray-800 px-5 py-3 border-b border-gray-200 dark:border-gray-700">
                    <h3 className="font-medium text-gray-900 dark:text-white">Improvement Suggestions</h3>
                  </div>
                  <div className="max-h-[500px] overflow-y-auto p-5">
                    {resumeLines.some((_, i) => getSuggestionForLine(i, resumeLines[i])) ? (
                      <div className="space-y-6">
                        {resumeLines.map((line, index) => {
                          const suggestions = getSuggestionForLine(index, line);
                          if (!suggestions) return null;
                          
                          return (
                            <div key={index} className="rounded-lg border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-700 dark:bg-gray-800">
                              <div className="flex items-start space-x-3 mb-3">
                                <div className="bg-blue-100 dark:bg-blue-900/30 rounded-md px-2.5 py-1 text-xs font-medium text-blue-700 dark:text-blue-300">
                                  Line {index + 1}
                                </div>
                                <div className="flex-1">
                                  <p className="text-sm text-gray-800 dark:text-gray-200 font-mono">
                                    {line || "\u00A0"}
                                  </p>
                                </div>
                              </div>
                              
                              <div className="border-t border-gray-100 dark:border-gray-700 pt-3 mt-3">
                                <p className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                                  Suggestions:
                                </p>
                                <ul className="space-y-3 mb-4">
                                  {suggestions.map((suggestion, idx) => (
                                    <li key={idx} className="flex items-start space-x-2.5 bg-gray-50 dark:bg-gray-900 p-2 rounded-md">
                                      <div className="mt-1.5 h-2.5 w-2.5 rounded-full bg-blue-400 flex-shrink-0"></div>
                                      <p className="text-sm text-gray-600 dark:text-gray-400">{suggestion}</p>
                                    </li>
                                  ))}
                                </ul>
                                <button
                                  onClick={() => handleLineClick(index, suggestions)}
                                  className="w-full flex items-center justify-center space-x-2 rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 transition-colors"
                                >
                                  <FiEdit3 className="h-4 w-4" />
                                  <span>Apply Best Suggestion</span>
                                </button>
                              </div>
                            </div>
                          );
                        })}
                      </div>
                    ) : (
                      <div className="text-center py-12 bg-gray-50 dark:bg-gray-800 rounded-lg">
                        <p className="text-sm text-gray-500 dark:text-gray-400">
                          No suggestions available for this resume.
                        </p>
                      </div>
                    )}
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
