#!/bin/bash

echo "🚀 Setting up Groq as Default AI Provider for Resume Checker"
echo "============================================================="

echo ""
echo "📋 To use Groq for all AI functions, you need to:"
echo ""
echo "1. Get your Groq API key from: https://console.groq.com/"
echo "2. Set the environment variable:"
echo "   export GROQ_API_KEY=your_actual_api_key_here"
echo ""
echo "3. Or add it to your shell profile (~/.zshrc, ~/.bashrc):"
echo "   echo 'export GROQ_API_KEY=your_actual_api_key_here' >> ~/.zshrc"
echo "   source ~/.zshrc"
echo ""
echo "4. Restart your server:"
echo "   npm run dev"
echo ""
echo "✅ Groq is already configured as the DEFAULT provider for:"
echo "   - Resume Analysis"
echo "   - ATS Scoring" 
echo "   - Content Improvement"
echo "   - Chat Assistant"
echo "   - Job Search"
echo ""
echo "🔑 No other configuration needed - just set your GROQ_API_KEY!"
echo ""
echo "🧪 Test it with:"
echo "   curl -X POST -H 'Content-Type: application/json' \\"
echo "     -d '{\"text\":\"Software Engineer with 5 years experience\"}' \\"
echo "     http://localhost:4000/api/resume/analyze"
